---
title: "draw_emission_2D_one_state"
author: "Ha Vu"
date: "10/18/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyr)
library(tidyverse)
library(ggplot2)
library(dplyr)
library(pheatmap)
source('/Users/vuthaiha/Desktop/window_hoff/source/summary_analysis/draw_emission_matrix_functions.R')
```
# Get the emission matrix into a dataframe
```{r}
num_state <- 100
num_exp <- 901
emission_fn <- '/Users/vuthaiha/Desktop/window_hoff/full_stacked_mouse/from_jason_061921/emissions/emissions_100_for_pheatmap.txt'
output_folder <- '/Users/vuthaiha/Documents/UCLA/mouse_fullStack/presentations/figures/'
emission_df <- as.data.frame(read.csv(emission_fn, sep = '\t', header = TRUE)) %>% arrange(assay_big_group, assay, organ_order, organ_group)
colnames(emission_df) <- c('experiments', paste0('S', seq(1,num_state)), colnames(emission_df)[102:length(colnames(emission_df))])
```

Get data of annotation of states
```{r}
annot_fn <- '/Users/vuthaiha/Desktop/window_hoff/full_stacked_mouse/from_jason_061921/state_annotation_processed.csv'
annot_df <- as.data.frame(read.csv(annot_fn, header = TRUE, stringsAsFactors = FALSE, sep = '\t'))
read_state_annot_df <- function(state_annot_fn){
	annot_df <- as.data.frame(read.csv(state_annot_fn, header = TRUE, stringsAsFactors = FALSE, sep = '\t'))
	tryCatch({
		annot_df <- annot_df %>% rename('state_group' = 'group')
		}, error = function (e) {message("tried to change column names in annot_df and nothing worth worrying happened")})
	annot_df <- annot_df %>% arrange(state_order_by_group) # order rows based on the index that we get from state_order_by_group column
	return(annot_df)	
}
annot_df <- read_state_annot_df(annot_fn)
head(annot_df)
```

```{r}
state_to_plot <- 37
state_mnemonics <- (annot_df %>% filter(state==state_to_plot) %>% select('mneumonics'))[[1]]
plot_df <- emission_df %>% select(paste0('S', state_to_plot))
plot_df$index <- seq(nrow(plot_df))
ggplot(data = plot_df, aes_string(x='index', y=paste0('S', state_to_plot))) + geom_line() + ggtitle(state_mnemonics) + theme_classic2() + 
  theme(axis.text.x=element_blank(), axis.ticks.x=element_blank(), axis.title.x = element_blank()) + 
  ylab('Emission probability')
  
save_fn <- file.path(output_folder, paste0(state_mnemonics, '_2DEmission.png'))
ggsave(save_fn, width = 8, height = 5)
```

