---
title: "draw_avg_gene_exp_heatmap"
author: "Ha Vu"
date: "3/30/2022"
output: html_document
---

```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
library(pheatmap)
library(RColorBrewer)
```

```{r}
state_annot_fn <- '/Users/vuthaiha/Desktop/window_hoff/full_stacked_mouse/from_jason_061921/state_annotation_processed.csv'
read_state_annot_df <- function(state_annot_fn){
	annot_df <- as.data.frame(read.csv(state_annot_fn, header = TRUE, stringsAsFactors = FALSE, sep = '\t'))
	tryCatch({
		annot_df <- annot_df %>% rename('state_type' = 'group')
		}, error = function (e) {message("tried to change column names in annot_df and nothing worth worrying happened")})
	annot_df <- annot_df %>% arrange(state_order_by_group) # order rows based on the index that we get from state_order_by_group column
	return(annot_df)	
}
state_annot_df <- read_state_annot_df(state_annot_fn)
state_color_df <- unique(state_annot_df%>% select(c('state_type', 'color')))
STATE_COLOR_MAPPING <- setNames(state_color_df$color, state_color_df$state_type)
CELL_TYPE_COLOR_MAPPING <- c('cerebellum'= '#C5912B', 'heart'= '#D56F80', 'intestine'= '#D0A39B', 'testes'= '#ACB9CA', 'spleen'= '#678C69', 'thymus'= '#C6E0B4', 'olfactory'= '#999999', 'mESC'= '#924965', 'mef_male'= '#C075C3', 'mef'= '#C075C3', 'brain'= '#C5912B', 'lung'= '#E41A1C', 'cortex'= '#C5912B', 'limb'= '#F182BC', 'placenta'= '#69608A', 'boneMarrow'= '#375623', 'kidney'= '#F4B084', 'liver'= '#9BC2E6')
calculate_gap_rows_among_state_groups <- function(state_annot_df){
	state_group_ordered_by_appearance <- unique(state_annot_df$state_type) # list of different state groups, ordered by how they appear in the heatmap from top to bottom
	count_df <- state_annot_df %>% count(state_type)
	count_df <- count_df[match(state_group_ordered_by_appearance, count_df$state_type),] # order the rows such that the state_type are ordered based on state_group_ordered_by_appearance
	results <- cumsum(count_df$n) # cumulative sum of the count for groups of states, which will be used to generate the gaps between rows of the heatmaps
	return(results)
}

get_cell_group_name <- function(cg){
  cg <- unlist(strsplit(cg, "_"))[1]
  if (endsWith(cg, '1') | endsWith(cg, '2')){
    cg <- substr(cg,1,nchar(cg)-1)
  }
  return(cg)
}

get_file_name_without_tail <- function(fn){
  fn_no_tail <- unlist(strsplit(fn, "[.]"))[1] 
  return(fn_no_tail)
}

get_cell_type_name <- function(cg){ # jsut get rid of the 1 or 2 at the end of the cell group name
  if (endsWith(cg, '_1') | endsWith(cg, '_2')){
    cg <- substr(cg,1,nchar(cg)-2)
  }

  if (endsWith(cg, '1') | endsWith(cg, '2')){
    cg <- substr(cg,1,nchar(cg)-1)
  }
  return(cg)
}
```

```{r}
fn <- '/Users/vuthaiha/Desktop/window_hoff/full_stacked_mouse/from_jason_061921/gene_exp/avg_gene_exp_per_state_per_ct.txt.gz'
df <- read.table(fn, sep = '\t', header = TRUE, row.names = 1)
df <- as.data.frame(t(df))
df$ct <- sapply(rownames(df), get_cell_type_name)
# get the mean expression per cell type per state across the different replicates
df <-  df %>% group_by(ct) %>% summarise(across(everything(), mean))
ct_list <- df$ct
df <- df %>% select(-c('ct'))
df <- as.data.frame(t(df)) # transpose again to its original form
colnames(df) <- ct_list
# rearrange the rows such that states of the same group are put together
state_annot_df <- read_state_annot_df(state_annot_fn)
df <- df %>% slice(state_annot_df$state)
rownames(df) <- state_annot_df$mneumonics
# create the df for annotationof rows in our heatmap
rownames(state_annot_df) <- state_annot_df$mneumonics
state_annot_df <- state_annot_df %>% select(state_type)
gap_row_indices <- calculate_gap_rows_among_state_groups(state_annot_df)
# create the df for annotations of columns in our heatmap
cell_group_df <- data.frame(ct = colnames(df))
cell_group_df$group <- sapply(cell_group_df$ct, get_cell_group_name)
# reorder the groups of cell types such that tissues that are similar are closer to each other
ordered_cg_list <- c('brain', 'cerebellum', 'cortex', 'mESC', 'mef', 'mef_male', 'placenta', 'boneMarrow', 'heart', 'intestine', 'kidney', 'liver', 'lung', 'spleen', 'testes', 'thymus', 'limb', 'olfactory')
ordered_cg_df <- data.frame(ct = character(), group = character())
for (cg in ordered_cg_list){
  this_cg_df <- cell_group_df %>% filter(group == cg)
  ordered_cg_df <- bind_rows(ordered_cg_df, this_cg_df)
}
rownames(ordered_cg_df) <- ordered_cg_df$ct
ordered_cg_df <- ordered_cg_df %>% select(group)
df <- df %>% select(rownames(ordered_cg_df)) # reorder the columns of df (df of average gene_exp)
break_list <- seq (0.1, 2.8, by = 0.1)
fn_no_tail <- get_file_name_without_tail(fn)
save_fn <- paste0(fn_no_tail, ".png")
pheatmap(df, breaks = break_list, color = colorRampPalette(rev(brewer.pal(n = 7, name = "RdYlBu")))(length(break_list)), annotation_row = state_annot_df, annotation_col = ordered_cg_df, annotation_colors = list(state_type = STATE_COLOR_MAPPING, group = CELL_TYPE_COLOR_MAPPING), gaps_row = gap_row_indices, fontsize =4.5, cluster_rows = FALSE, cluster_cols = FALSE, show_colnames = TRUE, filename = save_fn, cellwidth= 5) 
```